# create certs
.PHONY: create-certs
create-certs: 
	go run install.go --config ../resources/test/config.yml --certs


# create certs
.PHONY: create-token
create-token: 
	go run install.go --config ../resources/test/config.yml --token	