language: go

go:
  - 1.14.x
  - 1.15.x

before_install:
  - go get -v golang.org/x/lint/golint

script: make test

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
