rootUri: http://localhost:8080
redirectUri: http://localhost:8080/jwt-proxy/callback
wwwRootDir: www
jwt:
  publicKeyPath: certs/public.pem
  privateKeyPath: certs/private.pem
  signingMethod: RS256
  audience: your-audience
  subject: your-subject
  expirySeconds: 2592000