rootUri: http://localhost:8080
redirectUri: http://localhost:8080/callback
wwwRootDir: www
jwt:
  publicKeyPath: certs/public.pem
  privateKeyPath: certs/private.pem
  signingMethod: RS256
  audience: your-audience
  subject: your-subject
  expirySeconds: 2592000
providers:
  google:
    clientId: your-google-client-id
    clientSecret: your-google-secret
    scopes:
      - profile
  github:
    clientId: your-github-client-id
    clientSecret: your-github-secret
    scopes:
      - user
  facebook:
    clientId: your-facebook-client-id
    clientSecret: your-facebook-secret
    scopes:
      - public-profile