root-uri: http://localhost:8080
redirect-uri: http://localhost:8080/callback
jwt:
  signingMethod: RS256
  audience: your-audience
  issuer: you
  subject: your-subject
google:
  clientid: your-google-client-id
  clientsecret: your-google-secret
  scopes:
    - profile
github:
  clientid: your-github-client-id
  clientsecret: your-github-secret
  scopes:
    - user
facebook:
  clientid: your-facebook-client-id
  clientsecret: your-facebook-secret
  scopes:
    - public-profile