root_uri: http://localhost
redirect_uri: http://localhost/callback
test: configfile
jwt:
  signingMethod: RS256
  public_key: certs/public.pem
  private_key: certs/private.pem
  audience: your-audience
  issuer: you
  subject: your-subject
providers:
  google:
    client_id: your-google-client-id
    client_secret: your-google-secret
    scopes:
      - profile
  github:
    client_id: your-github-client-id
    client_secret: your-github-secret
    scopes:
      - user
  facebook:
    client_id: your-facebook-client-id
    client_secret: your-facebook-secret
    scopes:
      - public_profile
