rootUri: http://localhost:8080
redirectUri: http://localhost:8080/callback
wwwRootDir: www
jwt:
  signingMethod: RS256
  publicRSAKeyPath: ../test/public.pem
  privateRSAKeyPath: ../test/private.pem
  audience: your-audience
  issuer: you
  subject: your-subject
providers:
  google:
    clientId: your-google-client-id
    clientSecret: your-google-secret
    scopes:
      - profile
  github:
    clientId: your-github-client-id
    clientSecret: your-github-secret
    scopes:
      - user
  facebook:
    clientId: your-facebook-client-id
    clientSecret: your-facebook-secret
    scopes:
      - public_profile
