rootUri: http://localhost:8080
redirectUri: http://localhost:8080/jwt-proxy/callback
wwwRootDir: www
jwt:
  publicRSAKey:
  publicRSAKeyPath: certs/public.pem
  privateRSAKey:
  privateRSAKeyPath: certs/private.pem
  signingMethod: RS256
  audience: your-audience
  subject: your-subject
  issuer: you.com
  expirySeconds: 2592000
providers: