root_uri: http://localhost:8080
redirect_uri: http://localhost:8080/callback
jwt:
  signingMethod: RS256
  audience: stingray
  issuer: Lucas Buhlmann
  subject: It's a test
providers:
  google:
    client_id: your-google-client-id
    client_secret: your-google-secret
    scopes:
      - profile
  github:
    client_id: 4128b7915769705c628f
    client_secret: 0ea51e6d5ebc8cbb022784a29b0b274170d6ddba
    scopes:
      - user
  facebook:
    client_id: your-facebook-client-id
    client_secret: your-facebook-secret
    scopes:
      - public_profile
